obj-$(CONFIG_INTELLI_PLUG) += intelli_plug.o
obj-$(CONFIG_MSM_HOTPLUG) += msm_hotplug.o
obj-$(CONFIG_ALUCARD_HOTPLUG) += alucard_hotplug.o
obj-$(CONFIG_THUNDERPLUG_CONTROL) += thunderplug.o
obj-$(CONFIG_BRICKED_HOTPLUG) += bricked_hotplug.o
obj-$(CONFIG_HIMA_HOTPLUG) += hima_hotplug.o
obj-$(CONFIG_CLUSTER_PLUG)	+= cluster_plug.o
